"use striсt";
let redBlock = document.getElementById ('first');
redBlock.style.backgroundColor = 'red';
let blueBlock = document.getElementById ('second');
blueBlock.style.backgroundColor = 'blue';
let yellowBlocks = document.getElementsByClassName ('yellow');
yellowBlocks[0].style.backgroundColor = 'yellow';
yellowBlocks[yellowBlocks.length - 1].style.backgroundColor = 'yellow';
let greenBlock = document.getElementsByTagName('div');
greenBlock[3].style.backgroundColor = 'green';